### PR TITLE
addpkg(tur-hacking/burpsuite{,-pro}): 2023.12.1.5

### PR DESCRIPTION
**Pull request by knyipab**
Version higher than 2023.12.1.5 may require openjdk >= 21. 

LICENSE is from 
* https://portswigger.net/burp/eula/community
* https://portswigger.net/burp/eula/pro

### CODE REVIEW

**Comment by licy183** [comment]
I'm not sure whether burpsuite allows third party to redistribute their binaries or not.

**Comment by knyipab** [comment]
I am by no means expert on this. Just note that Kali (official) package burpsuite and AUR packages both versions.  
https://wiki.archlinux.org/title/Burp_Suite
https://www.kali.org/tools/burpsuite/

**Comment by licy183** [comment]
Kali packages burpsuite community so I think it is acceptable to package it too.

AUR actually performs on device build and it is different from TUR, so I think it is better to package an installer script for `burpsuite-pro`.

**Comment by knyipab** [comment]
By installer script, do you mean shell script like this?
```bash
termux_step_create_debscripts() {
	cat <<- EOF > ./postinst
		# ...
	EOF

	cat <<- EOF > ./prerm
		# ...
	EOF
}
```

**Comment by licy183** [comment]
Yes. `burpsuite-pro` can be downloaded in `postinst`.

**Review by licy183 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
