### PR TITLE
new package: abuse

### LINKED ISSUE #64: Package request: Free Abuse / fRaBs
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name: (Free) Abuse
Homepage: https://github.com/Xenoveritas/abuse
Source link:

**Additional Info:**

In short, the working product consists of 2 parts - the engine (given in the link) and the game files that are in my repository.

I generally compiled the game engine myself on Termux. Unfortunately it doesn't work with Clang, even after correcting the compilation errors, the application doesn't start after SegFault.

Instead, it works when compiled with GCC. What I don't know is how to make a proper build.sh that would build the engine. It would be nice if someone writes such a file and makes it available, I will try to extend it to use fRaBs (or do it manually :P)

https://github.com/IntinteDAO/Frabs

### PR DESCRIPTION
**Pull request by licy183**
Closes #64

### CODE REVIEW

**Comment by licy183** [comment]
@IntinteDAO Hi, could you please test this package?

**Comment by IntinteDAO** [comment]
@licy183 

Sorry, how Can I download Deb file? I don't have on this computer TUR build scripts :(

**Comment by licy183** [comment]
You could download it from here https://github.com/termux-user-repository/tur/actions/runs/3367396351

**Comment by T-Dynamos** [comment]
Works, 
Screenshot_2022-11-06-09-21-26-632_com realvnc viewer android

**Pull request merged**
