### PR TITLE
New Package: clspkg

### PR DESCRIPTION
**Pull request by turbomaster95**
I Have added a package called 'clspkg'
it adds the command 'cls' to clear the screen

i am using gh cli to type this

### CODE REVIEW

**Comment by turbomaster95** [comment]
pls merge

**Comment by T-Dynamos** [comment]
I have one question: why?
Why can't you do `alias cls=clear` or `echo "clear" > $PREFIX/bin/cls && chmod +x $PREFIX/bin/cls`
What special does `clspkg` do?

**Comment by licy183** [comment]
I don't think this package will be added, see our package policy.

```
TUR may not accepts these packages:
Few lines of scripting code.
```

**Comment by turbomaster95** [comment]
i just had this same conversation with two prople on the official termux-packages repo

**Pull request closed without merging**
