### PR TITLE
New package: Python-Cairo

### PR DESCRIPTION
**Pull request by IntinteDAO**

### CODE REVIEW

**Comment by licy183** [comment]
Actually, this cannot work properly. It installs the package in `$PREFIX/lib/python3` rather than `$PREFIX/lib/python3.10` and will not handle `easy_install.pth`...

**Comment by IntinteDAO** [comment]
>  It installs the package in $PREFIX/lib/python3/dist-packages rather than $PREFIX/lib/python3.10/site-packages

As far as I can see, it's the same in Debian. 
Nevertheless, actually the library does not work. Do you have any idea what to do about it? Especially since compiling this library is a big problem :P

**Comment by licy183** [comment]
@IntinteDAO Hello, please test this package as I'm not familiar with it. Thanks!

**Comment by IntinteDAO** [comment]
@licy183 Hello

Your script is detected by Python (compared to mine :/), but it doesn't detect some internal modules that should be.

The pip install pycairo works fine, but Cairo is used by a large number of applications. That's why I wanted to port it to Termux.

```
~ $ python3
Python 3.10.7 (main, Sep  8 2022, 06:55:17) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pycairo-1.21.0-py3.10-linux-aarch64.egg/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ModuleNotFoundError: No module named 'cairo._cairo'
```

**Comment by licy183** [comment]
It seems a common problem for cross-compiled python packages after python updates to 3.10.7, such as python-numpy from the main repository. Should be fixed now. Please test it again!

**Comment by IntinteDAO** [comment]
> It seems a common problem for cross-compiled python packages after python updates to 3.10.7, such as python-numpy from the main repository. Should be fixed now. Please test it again. Thanks!

Works!

Remember to remove the tab from lines 64, 68, 70 and 74 in build.sh, otherwise an error pops up.

```
cat <<- EOF > ./postinst
	#!$TERMUX_PREFIX/bin/sh
	echo "Installing $TERMUX_PKG_NAME..."
	echo "./${_EGGDIR}" >> $TERMUX_PREFIX/lib/python${_PYTHON_VERSION}/site-packages/easy-install.pth
EOF

cat <<- EOF > ./prerm
	#!$TERMUX_PREFIX/bin/sh
	echo "Removing $TERMUX_PKG_NAME..."
	sed -i "/\.\/${_EGGDIR//./\\.}/d" $TERMUX_PREFIX/lib/python${_PYTHON_VERSION}/site-packages/easy-install.pth
EOF
```

**Pull request merged**
