### PR TITLE
Call entrypoint on docker-exec

### PR DESCRIPTION
**Pull request by Kapral67**
## BREAKING CHANGE

- Breaks [common-files/build-termux-docker.sh](https://github.com/termux-user-repository/tur/blob/57b28c4921381567294b456370e2b4818e5d2512/common-files/build-termux-docker.sh) unless termux-user-repository/termux-docker#1 is merged

### CODE REVIEW

**Comment by licy183** [comment]
`/entrypoint.sh` doesn't exist in Dockerfile IIRC...

**Comment by Kapral67** [comment]
Your right, but I am looking into opening a pull request merging termux/termux-docker#49 into termux-user-repository/termux-docker since they have implemented dns resolution upstream. this pr is just a placeholder for now until then.

**Comment by licy183** [comment]
It is not possible to add `dnsmasq`. TUR's termux-docker image contains files from Android 7, where `dnsmasq` doesn't exist.

**Comment by Kapral67** [comment]
we can, hopefully, extract dnsmasq binary and libs (libcutils.so) from API 24 images:

arm: https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-24_r07.zip
x86: https://dl.google.com/android/repository/sys-img/google_apis/x86-24_r27.zip

**Pull request merged**
