### PR TITLE
new package : metasploit

### PR DESCRIPTION
**Pull request by T-Dynamos**
@2096779623 Please check if everything is correct

### CODE REVIEW

**Comment by 2096779623** [comment]
Thanks for PR, rename package name to `metasploit-framework` .

**Comment by 2096779623** [comment]
Please enable `TERMUX_PKG_AUTO_UPDATE`,
msf releases once a week.

**Comment by 2096779623** [comment]
Maybe we need to use this package as an installer like before termux.

https://github.com/sqlsec/termux-sec-packages/tree/main/metasploit

**Comment by T-Dynamos** [comment]
> Maybe we need to use this package as an installer like before termux.
> 
> https://github.com/sqlsec/termux-sec-packages/tree/main/metasploit

Let's just give a try like this

**Comment by T-Dynamos** [comment]
```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/3.0.0 directory.
```
Why this? If the prefix is `TERMUX_PREFIX`. Let's try building this on termux itself

**Comment by T-Dynamos** [comment]
```
❯ ./build-package.sh tur/metasploit-framework/
termux - building metasploit-framework for arch aarch64...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
termux-elf-cleaner is already the newest version (2.1.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Building dependency libc++ if necessary...
termux - building libc++ for arch aarch64...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
termux-elf-cleaner is already the newest version (2.1.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
cp: cannot stat '/data/data/com.termux/files/home/.termux-build/_cache/android-r25-api-24-v1/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so': No such file or directory
```
Why?

**Comment by T-Dynamos** [comment]
I was able to build nokogiri with 
`LDFLAGS="-Wl,--no-as-needed,-liconv"`

**Comment by 2096779623** [comment]
```bash
Building native extensions. This could take a while...
ERROR:  Error installing actionpack:
	ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/gems/racc-1.6.0/ext/racc/cparse
/usr/bin/ruby3.0 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20220910-2668-y6s3fx.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/gems/racc-1.6.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/extensions/x86_64-linux/3.0.0/racc-1.6.0/gem_make.out
Error: Process completed with exit code 1.
```
You should linker `$TERMUX_PREFIX/include/ruby-3.1.0/ruby/ruby.h` .

**Pull request closed without merging**
