### PR TITLE
CI: switch to qemu for on-device build

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by T-Dynamos** [comment]
Not yet ready to merge?

**Comment by licy183** [comment]
> Not yet ready to merge?

I'm not sure whether it is a good decision to merge this. Using qemu will make it slow to compile packages for arm/aarch64, but the self-hosted runner is owned by me, and it will not be always online and may have some connection issues to GitHub because it is hosted in China.

**Comment by T-Dynamos** [comment]
Please merge this for the time being, I need to build blender.

**Comment by licy183** [comment]
Ah... My aarch64 server is going to be expired. So I'll merge this PR now...

**Comment by licy183** [comment]
When building `python-tokenizers`, it takes about 1 hour on aarch64 with qemu and 10 mins on x86_64... Maybe CircleCI is a good alternative...

**Comment by T-Dynamos** [comment]
CircleCi will able to build blender?

**Comment by T-Dynamos** [comment]
@licy183 I think we need to use circle ci, I highly doubt [this action](https://github.com/termux-user-repository/tur/actions/runs/7306967550/job/19912194867?pr=747) will be completed in less than 6hrs (51 mins to build on x86_64, 51 mins * 6 for aarch64?).

**Comment by licy183** [comment]
> @licy183 I think we need to use circle ci, I highly doubt [this action](https://github.com/termux-user-repository/tur/actions/runs/7306967550/job/19912194867?pr=747) will be completed in less than 6hrs (51 mins to build on x86_64, 51 mins * 6 for aarch64?).

Ah... I still don't know how to detect whether a workflow triggered via a Pull Request or via commit to master branch on CircleCI's GitHub App workflow. From August 2023, they have closed the registration through GitHub OAuth App. So it is hard to use CircleCI...

**Comment by T-Dynamos** [comment]
I have a circleci account I can give authtoken. can we run pipeline on pr or merge https://circleci.com/docs/oss/#only-build-pull-requests. should I try doing it?

**Comment by licy183** [comment]
You can give it a try.

**Pull request merged**
