### PR TITLE
chore(hacking): remove some hacking packages to another repository

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by 2096779623** [comment]
Also need update https://github.com/termux/termux-packages/blob/master/packages/tur-repo/build.sh ?

**Comment by licy183** [comment]
> Also need update https://github.com/termux/termux-packages/blob/master/packages/tur-repo/build.sh ?

I don't think we need to update it. Actually, one reason to split packages to another TUR repository is to make it hard to install hacking-related packages.

**Comment by kcubeterm** [comment]
how will one install hacking packages then ?

**Comment by licy183** [comment]
> how will one install hacking packages then ?

Someone must manually add `tur-hacking` to `$PREFIX/etc/apt/sources.list.d/tur.list`. Should we update `README`?

**Comment by kcubeterm** [comment]
if the point is to make installing hard such packages for skids. then its seems good, then why even add that in `README` then.  Keep it secret :)

**Pull request merged**
