### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by E343IO**
ADDED / UPDATED LIB. SECTION =`wget`

SRCURL = `https://github.com/E343IO/shark/archive/refs/tags/v2.5.1.zip` 

SHA256 = `b6cf74584f85acd9a110c04f398b1498972159c4d70a617abd0444e5c777f382` 

Thx for your support @licy183

### CODE REVIEW

**Comment by E343IO** [comment]
@licy183 why it haven't update yet in tur-repo 
While i'd reinstall by `purge`  the pkg tur-repo

#### Check img. Below


Screenshot_20230324_212434_Termux

**Comment by T-Dynamos** [comment]
Check if `tur-hacking` is in `$PREFIX/etc/apt/sources.list.d/tur.list`. of not add it and then update package.

**Comment by E343IO** [comment]
> Check if `tur-hacking` is in `$PREFIX/etc/apt/sources.list.d/tur.list`.If not add it and then update package.

U' àre ŕight brother!!!!, now i can do this silly mistakes then what about actual users?
By default why it can't be ìn `source.list`

**Comment by T-Dynamos** [comment]
> U' àre ŕight brother!!!!, now i can do this silly mistakes then what about actual users?
By default why it can't be ìn source.list
Because termux doesn't support hacking. Read : https://wiki.termux.com/wiki/Hacking. That's why `tur-hacking` not enabled by default

**Comment by E343IO** [comment]
> > U' àre ŕight brother!!!!, now i can do this silly mistakes then what about actual users?
> > By default why it can't be in source.list
> 
> Because termux doesn't support hacking. Read : https://wiki.termux.com/wiki/Hacking. That's why `tur-hacking` not enabled by default

Oh yeah got it bruh! Thx

**Pull request merged**
