### PR TITLE
new package : python-pygame

### PR DESCRIPTION
**Pull request by T-Dynamos**

### CODE REVIEW

**Comment by T-Dynamos** [comment]
```
/bin/sh: 1: sdl2-config: not found
```
I am unable to solve this I even added sdl2 in `TERMUX_PKG_BUILD_DEPENDS`

**Comment by ifurther** [comment]
maybe try to set PATH $TERMUX_PREFIX/bin

**Comment by T-Dynamos** [comment]
Same, not working

**Comment by ifurther** [comment]
the patch file is not needed.

**Comment by ifurther** [comment]
Hi I success build it and and build.sh is in the [commit](https://github.com/ifurther/tur/commit/c2d9ac2d26f2bbfc380d498dbb50477c8fb960b6)

**Comment by IntinteDAO** [comment]
I was slowed :P But maybe it's useful for someone
```
TERMUX_PKG_HOMEPAGE=https://www.pygame.org
TERMUX_PKG_DESCRIPTION="SDL bindings for games development"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@fervi"
TERMUX_PKG_VERSION=2.1.2
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/pygame/pygame/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=6fbdbdcdb7382998eb0f94a6d2e7066c9c93aa21b61c1b3b9f1fe7dfc0c56148
TERMUX_PKG_DEPENDS="python, sdl, sdl2, sdl2-image, sdl2-mixer, sdl2-net, sdl2-ttf, portmidi"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM_INDEPENDENT=false

_PYTHON_VERSION=$(. $TERMUX_SCRIPTDIR/packages/python/build.sh; echo $_MAJOR_VERSION)

termux_step_pre_configure() {
	export PATH="$PATH:/data/data/com.termux/files/usr/bin"
        export PYTHONPATH=${TERMUX_PREFIX}/lib/python3.10/site-packages/
	termux_setup_python_crossenv
	pushd $TERMUX_PYTHON_CROSSENV_SRCDIR
	_CROSSENV_PREFIX=$TERMUX_PKG_BUILDDIR/python-crossenv-prefix
	python${_PYTHON_VERSION} -m crossenv \
		$TERMUX_PREFIX/bin/python${_PYTHON_VERSION} \
		${_CROSSENV_PREFIX}
	popd
	. ${_CROSSENV_PREFIX}/bin/activate
}

termux_step_make_install() {
	DEBVER=$TERMUX_PKG_VERSION \
		python setup.py install --force --prefix $TERMUX_PREFIX
}

```

**Comment by T-Dynamos** [comment]
@licy183  PR is ready to be merged

**Pull request merged**
