### PR TITLE
New package: arpack-ng

### PR DESCRIPTION
**Pull request by ifurther**

### CODE REVIEW

**Comment by T-Dynamos** [comment]
```
22-08-13T00:46:31.7586771Z   Tell CMake where to find the compiler by setting either the environment
2022-08-13T00:46:31.7587129Z   variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
2022-08-13T00:46:31.7587467Z   path to the compiler, or to the compiler name if it is in the PATH.
```
set `FC` or setting `PATH`

**Comment by licy183** [comment]
It seems that a toolchain with fortran support is needed to compile this package. I will move the host-build step in gcc, which compiles a gcc toolchain with fortran support, to a new git repository if I have some time. Or try to use android-gfortran https://github.com/buffer51/android-gfortran.

**Comment by ifurther** [comment]
Maybe it should need the new repository

**Comment by IntinteDAO** [comment]
@licy183 

> It seems that a toolchain with fortran support is needed to compile this package.

Isn't flang a Fortran Compiler? Or it is not enough?

**Comment by licy183** [comment]
> Isn't flang a Fortran Compiler? Or it is not enough?

`flang` from `llvm-project` cannot be used for cross-compiling currently, as it cannot produce `PIC (position-independent code)` but `PIC` is always needed for Android 7.0. `classic-flang` is also difficult to cross-compile, as it doesn't support cross-compile natively.

**Comment by licy183** [comment]
@ifurther Hello, please test whether this package works fine if it is convenient for you. Thanks!

**Pull request merged**
