### PR TITLE
new pkgs: openalut , python-opengl, trigger

### LINKED ISSUE #129: Fervi's Packages
Hi. Unfortunately I have had some minor health issues recently and will not be involved in the development of Termux.

I have 3 packages here that I think you can add to TUR. 
The first is python-opengl, it seems to work (although there is no OpenGL support in Termux)
The second is openalut, which is required for Trigger Rally
The third is Trigger Rally - the game works, but unfortunately due to the lack of OpenGL, it runs terribly slow on LLVMPipe.

[termux-packages.tar.gz](https://github.com/termux-user-repository/tur/files/9839887/termux-packages.tar.gz)

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #129

### CODE REVIEW

**Comment by 2096779623** [comment]
add `openal-soft` to `TERMUX_PKG_BUILD_DEPENDS` .

**Comment by licy183** [comment]
Thanks for your contribution! Could you please split them into seperated commit? I think one commit should only contain one package.

**Comment by T-Dynamos** [comment]
Done!

**Comment by licy183** [comment]
Thanks!

**Pull request merged**
