### PR TITLE
New package: icewm

### PR DESCRIPTION
**Pull request by IntinteDAO**

### CODE REVIEW

**Comment by IntinteDAO** [comment]
@licy183 
Do you have any ideas? It works like a charm on my Termux TUR Build System

**Comment by 2096779623** [comment]
Add `libxcomposite` to `TERMUX_PKG_DEPENDS` .

https://github.com/ice-wm/icewm/blob/master/src/CMakeLists.txt#L170

**Comment by IntinteDAO** [comment]
Do you have a artifact package to download? I don't know how to do it :/

But I believe it work, because the local version works

**Comment by licy183** [comment]
https://github.com/termux-user-repository/tur/actions/runs/5713154514

**Comment by IntinteDAO** [comment]
Works for me.

Ofc this is DE, it might contains some bugs, but I don't see any. It works great on Termux.

**Comment by licy183** [comment]
I'll merge this. Thanks for your contribution!

**Pull request merged**
