### PR TITLE
addpkg(tur/supertuxkart): Kart racing game featuring Tux and his friends

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/termux/termux-packages/issues/20801

### CODE REVIEW

**Comment by Grimler91** [comment]
Really cool addition, thanks for porting it :) 

You mentioned splitting binaries and data in the other issue. How large would a platform independent data subpackage be? Saving hosting space would be nice no matter if it is hosted in tur or main repo

**Comment by TomJo2000** [comment]
The commit message should probably be `addpkg(tur/supertuxkart): 1.4`

**Comment by Biswa96** [comment]
> You mentioned splitting binaries and data in the other issue. How large would a platform independent data subpackage be?

I have not tried that and I am not sure if game assets/data can be provided sepaately. 

```
$ du -h -d 0 $PREFIX/share/supertuxkart/data/
718M    /data/data/com.termux/files/usr/share/supertuxkart/data/
```

**Comment by TomJo2000** [comment]
<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux-user-repository/tur/actions/runs/9846344033?pr=1115).
image


After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>

```bash
# finding out what architecture you need
# architecture is just below the TERMUX_VERSION
termux-info

# e.g.
# [...]
# TERMUX_MAIN_PACKAGE_FORMAT=debian
# TERMUX_VERSION=0.118.0
# TERMUX__USER_ID=0
# Packages CPU architecture:
# aarch64
# [...]

# =======================

# make sure `unzip` and `tar` are installed using
pkg install unzip tar

# unzip the artifact (if you have a different architecture this might be arm, i686 or x86_64 instead)
unzip debs-aarch64-*.zip

# untar the artifact
tar xf debs-aarch64-*.tar

# You should now have a debs/ directory in your current working directory
# Install the packages from the local source using
pkg install -- ./debs/*.deb

# to clean up, you can remove the debs/ directory, .tar file and .zip file
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```

</p>
</details>

**Comment by licy183** [comment]
718M is too large for GitHub Release. It would be better to split them.

**Comment by licy183** [comment]
Thanks!

**Pull request merged**
