### PR TITLE
tur-on-device(blender): update to latest commit

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #724, #615

### CODE REVIEW

**Comment by MmyGgithubAaccount** [comment]
Errors out with:
`Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py", line 1753, in register
    blender_ui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 525, in register
    bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT'
Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py", line 44, in register
    gui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 218, in register
    register_message_bus()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 168, in register_message_bus
    bpy.msgbus.subscribe_rna(
TypeError: subscribe_rna: struct FileAssetSelectParams does not contain property asset_library_ref
26170 killed by signal 4`

Tried to run with `termux-x11 :1 -xstartup "dbus-launch --exit-with-session blender"`

**Comment by T-Dynamos** [comment]
> Errors out with: `Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py Traceback (most recent call last): File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable mod.register() File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py", line 1753, in register blender_ui.register() File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 525, in register bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT' Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py Traceback (most recent call last): File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable mod.register() File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py", line 44, in register gui.register() File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 218, in register register_message_bus() File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 168, in register_message_bus bpy.msgbus.subscribe_rna( TypeError: subscribe_rna: struct FileAssetSelectParams does not contain property asset_library_ref 26170 killed by signal 4`
> 
> Tried to run with `termux-x11 :1 -xstartup "dbus-launch --exit-with-session blender"`

This error is caused by android killing blender, maybe you need to disable battery optimisations.

**Comment by MmyGgithubAaccount** [comment]
It crashes at the same point everytime so I don't think it's battery optimization related (which is already disabled). Plus, from my limited understanding, kill signal 4 means an illegal instruction was sent so something else is happening.
Here is the [tombstone](https://github.com/termux-user-repository/tur/files/13792291/tombstone_31.txt) file generate if that helps

**Comment by T-Dynamos** [comment]
> It crashes at the same point everytime so I don't think it's battery optimization related (which is already disabled). Plus, from my limited understanding, kill signal 4 means an illegal instruction was sent so something else is happening. Here is the [tombstone](https://github.com/termux-user-repository/tur/files/13792291/tombstone_31.txt) file generate if that helps

Please open a new issue.

**Pull request merged**
