### PR TITLE
addpkg(tur/leanify): 0.4.3+20231217

### PR DESCRIPTION
**Pull request by TomJo2000**
Requested in: 
- termux/termux-packages#20885

> [!NOTE]
> Checklist:
> - [x] Builds locally
> - [ ] Builds on CI
> - [x] Tested on device (Android 13, AArch64, Fairphone 5)

<h1><em></em></h1> 

@TPS, if you wouldn't mind I'd appreciate if you could check the package for correct functioning.
I just did a basic "does it print its help and version information" test.
Instructions below.

<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux-user-repository/tur/actions/runs/9987167934).
Screenshot_20240619_232413

After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>

```bash
# finding out what architecture you need
# architecture is just below the TERMUX_VERSION
termux-info

# e.g.
# [...]
# TERMUX_MAIN_PACKAGE_FORMAT=debian
# TERMUX_VERSION=0.118.0
# TERMUX__USER_ID=0
# Packages CPU architecture:
# aarch64
# [...]

# =======================

# make sure `unzip` and `tar` are installed using
pkg install unzip tar

# unzip the artifact (if you have a different architecture this might be arm, i686 or x86_64 instead)
unzip debs-aarch64-*.zip

# untar the artifact
tar xf debs-aarch64-*.tar

# You should now have a debs/ directory in your current working directory
# Install the packages from the local source using
pkg install -- ./debs/*.deb

# to clean up, you can remove the debs/ directory, .tar file and .zip file
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```

</p>
</details>

### CODE REVIEW

**Comment by TPS** [comment]
@TomJo2000 There're no artifacts built?  How should I test?

**Comment by TomJo2000** [comment]
Whoops, wrong link.
Should have been:
https://github.com/termux-user-repository/tur/actions/runs/9987167934

**Comment by TPS** [comment]
@TomJo2000 `aarch64` worked just fine on all my test files.

**Comment by TomJo2000** [comment]
Sounds good to me.

You'll be able to install the package normally by using:
```bash
pkg i tur-repo
pkg i leanify
```
after it is merged.

**Comment by TPS** [comment]
@TomJo2000 Thanks _very_ much.  You've been amazing. 🙇🏾‍♂️

**Comment by TPS** [comment]
@TomJo2000 None of the improvements since this initial publishing have updated to the repo.  Should these be picked up automatically?

**Comment by TomJo2000** [comment]
> @TomJo2000 None of the improvements since this initial publishing have updated to the repo. Should these be picked up automatically?

That is unfortunately to be expected.
The auto update system work off of release tags,
so since there hasn't been a new tag published on the source repo since 2015 there is no way for the auto update system to know that a new release is available for it to build.

Because of that I didn't enable auto updates for this package at the time it was merged.

It looks like new commits started about 2 weeks ago, I can update the package to the latest commit,
however unless upstream starts releasing new tags again there is no way to automate those updates for the package.

**Pull request merged**
