### PR TITLE
new package: mesa-zink

### LINKED ISSUE #271: [Package]: Mesa-Zink (?)
### Name

Mesa

### Home page URL

_No response_

### Source code URL

https://gitlab.freedesktop.org/mesa/mesa.git

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

I found this tutorial:
https://raw.githubusercontent.com/ThieuMinh26/Proot-Setup/main/Zink

It's about using Zink in Termux, so you've got 3D Acceleration (on Termux-X11). It's not the best option, but maybe we should get it as an alternative for mesa.

I think newest version of Zink require some Vulkan extensions that Android Phone don't support, but this one works (for me at least).

I don't know how to set potential "mesa-zink" as "mesa" alternative that will work for all package, but maybe you know how to set it

### PR DESCRIPTION
**Pull request by licy183**
These packages are tested on Adreno (TM) 660 and work fine.

Closes #271.

CC: @IntinteDAO

### CODE REVIEW

**Comment by IntinteDAO** [comment]
I will test it soon (I hope :P)

I wonder if these packages can be used to compile virgl on the new mesa. In theory by using VirGL Overlay (Android app) you can also have 3D acceleration.

I will check on the current mesa with Zink what you have provided, maybe it will be possible to transfer the most important patches to the Mesa developed by Termux.

**Comment by licy183** [comment]
> I wonder if these packages can be used to compile virgl on the new mesa. In theory by using VirGL Overlay (Android app) you can also have 3D acceleration.

Of cource it is possible. If this package is installed to `opt` rather than `prefix`, then it will be possible to do this.

> I will check on the current mesa with Zink what you have provided, maybe it will be possible to transfer the most important patches to the Mesa developed by Termux.

Emmm... Actually I have worked on it, but it is quite hard anyway. Lots of commits should be reverted and it requires lots of work every time `mesa` updates.

**Comment by IntinteDAO** [comment]
@licy183

> Applying patch: enable-system_has_kms_drm-for-android.patch
Applying patch: fix-for-x11.patch
Applying patch: meson.build.patch
Applying patch: src-gallium-drivers-llvmpipe-lp_screen.c.patch
Applying patch: vtest-socket-path.patch
Applying patch: zink.patch
1 out of 1 hunk FAILED -- saving rejects to file src/egl/main/egldisplay.h.rej

I think zink.patch is little broken.

___

Anyway, if you want you can check also this project. But I'm not sure if it is possible to use this on Termux:
https://github.com/alexvorxx/Zink-Mesa-Xlib

**Comment by licy183** [comment]
I'll merge this after a day. If there is any bug, please let me know. Thanks!

Test commands:
zink without virgl: `GALLIUM_DRIVER=zink glmark2`
zink with virgl: In a session `GALLIUM_DRIVER=zink virgl_test_server --use-egl-surfaceless --use-gles`, and in another session `GALLIUM_DRIVER=virpipe glmark2`.

**Comment by IntinteDAO** [comment]
@licy183 Sadly doesn't work on my phone. Most OpenGL apps crash when using this package, but recompiled from script - works.

Not sure how to debug it

**Comment by licy183** [comment]
> @licy183 Sadly doesn't work on my phone. Most OpenGL apps crash when using this package, but recompiled from script - works.
> 
> Not sure how to debug it

Emmm... I don't know why the reason. Maybe you can using the zink driver with `ZINK_DESCRIPTORS=lazy MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.0 GALLIUM_DRIVER=zink glmark2`?

**Comment by IntinteDAO** [comment]
From Mesa-Zink package:
obraz

From Mesa-Zink source:
obraz

**Comment by licy183** [comment]
Emmm... But it works on my device.
image
Maybe the XWayland is the reason?

**Comment by IntinteDAO** [comment]
That wouldn't explain why the hand-compiled Mesa works for me. I know of no other hypothesis at all.

Maybe some patch does it, I'll have to test.

**Comment by licy183** [comment]
The script will override files in `libepoxy` too. Maybe that matters?

**Comment by licy183** [comment]
I may know the reason. Termux has already switched the OpenGL libraries to `libglvnd`. If you use that build script, the all the OpenGL libraries wiill be overridden. You can to install them forcedly using `apt install --reinstall libglvnd mesa-zink libepoxy` and try to test again.

**Comment by IntinteDAO** [comment]
@licy183 Works! Thank you!

**Pull request merged**
