### PR TITLE
new package: code-server

### LINKED ISSUE #34: [Package request] code server
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name:code-server
Homepage:https://github.com/coder/code-server
Source link:https://github.com/coder/code-server/archive/refs/tags/v4.5.0.tar.gz

**Additional Info:**
I don't know how to build nodejs packages

### PR DESCRIPTION
**Pull request by licy183**
Closes #34

### CODE REVIEW

**Comment by licy183** [comment]
Tests are fine on my device. @T-Dynamos Could you please test this package?

**Comment by licy183** [comment]
It seems that plugins cannot work...

**Comment by licy183** [comment]
Emmm... Now it seems to work fine.

**Comment by T-Dynamos** [comment]
```
writev(3, [{iov_base="\0", iov_len=1}, {iov_base="\1\n", iov_len=2}, {iov_base="\262Zbc&\360\223\21", iov_len=8}, {iov_base="\6", iov_len=1}, {iov_base="linker\0", iov_len=7}, {iov_base="CANNOT LINK EXECUTABLE \"/data/da"..., iov_len=120}], 6) = 139
close(3)                                = 0                exit_group(1)                           = ?
+++ exited with 1 +++
```
Exits with code 1

**Comment by T-Dynamos** [comment]
Works after upgrade

**Comment by licy183** [comment]
... I can't reproduce it. Which architecture is your device?

**Comment by licy183** [comment]
OK... So it is ready to merge?

**Comment by T-Dynamos** [comment]
Screenshot_2022-11-02-17-42-05-847_com android chrome
Yes merger it

**Pull request merged**
