### PR TITLE
add(tur): blender deps

### PR DESCRIPTION
**Pull request by T-Dynamos**
As Blender does not support cross-compiling, I decided to use Tur-on-device. In order to build Blender, I need these dependencies, as they would not be accepted in termux-packages.

### CODE REVIEW

**Comment by T-Dynamos** [comment]
Do I need to split commits?

**Comment by licy183** [comment]
> Do I need to split commits?

I think it is better.

**Comment by T-Dynamos** [comment]
@licy183 It's ready to be merged!

**Comment by licy183** [comment]
Thanks!

**Pull request merged**
